
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(Pipelinelevelvariable)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: java -version
    - bash: node --version
    - bash: python --version
    - bash: mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'


# - stage: DevDeploy
#   variables:
#   environment: Dev
#  jobs:
# - job:  DevDeployJob
#    steps:
#    - bash: echo DevDeployJob
#- stage: QADeploy
#  variables:
#   environment: QA
#  jobs:
#  - job:  QADeployJob
#    steps:
#    - bash: echo QADeployJob
#- stage: ProdDeploy
#  jobs:
#  - job:   ProdDeployJob
#    steps:
#    - bash: echo ProdDeployJob


