
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(Pipelinelevelvariable)
- stage: DevDeploy
  variables:
   environment: Dev
  jobs:
  - job:  DevDeployJob
    steps:
    - bash: echo DevDeployJob
- stage: QADeploy
  variables:
   environment: QA
  jobs:
  - job:  QADeployJob
    steps:
    - bash: echo QADeployJob
- stage: ProdDeploy
  jobs:
  - job:   ProdDeployJob
    steps:
    - bash: echo ProdDeployJob


